### ISSUE TITLE
Darwin mmap error

### ISSUE THREAD

**Issue by jknotts** [jknotts/aqualid#1]
mmap is currently the default handler in the DataFile class but when running aqualid on Darwin this error is shown: "SystemError: mmap: resizing not available--no mremap()".

**Comment by menify** [comment]
Good catch. Do you have any idea how to fix this?
As workaround SQLite could be used - option "--use_sqlite"

**Comment by jknotts** [comment]
Thanks for the tip on using the --use_sqlite option. So I don't really know how to solve this problem as it exists on both Darwin and FreeBSD. I did some research and it seems like its been a problem for some time. One option would be to default to your IOFile class for both Darwin and FreeBSD otherwise use the MMapFile class. I saw some suggestions on how to possibly address this issue but I don't know how it would affect performance: http://marc.info/?l=pypy-svn&m=130390787520440&w=2 and http://stackoverflow.com/questions/3521303/is-there-really-no-mremap-in-darwin If I come up with a better solution I will let you know.

**Comment by menify** [comment]
I agree. We can use IOFile on FreeBSD/Darwin.
I would prefer to avoid hardcoding specific platform.
Will the following check work?:
class _MmapFile( object ):
  
  def   __init__(self, filename ):
    ...
    size = memmap.size()
    memmap.resize( size + mmap.ALLOCATIONGRANULARITY )
    memmap.resize( size )

The idea is - if a system doesn't support resize then this code will raise an exception and IOFile will be used.

**Comment by jknotts** [comment]
Yea I think that will work, plus it follows a more pythonic solution using the try/except instead of hard coding platforms.

**Comment by jontayesp** [comment]
So I would like to suggest another idea. Instead of actually resizing the file (to see if resize is available), why not quickly test an anonymous map in memory?

```python
def is_resize_available():
  mm = mmap.mmap(-1, 1)
  try:
    mm.resize(1)
  except SystemError:
    return False
  else:
    return True
  finally:
    mm.close()
```

And before we instantiate the wrapper, we can check if resize exists:

```python
    if is_resize_available():
      self.handle = _MmapFile( filename )
    else:
      self.handle = _IOFile( filename )
```

I think this would be more efficient since we are only resizing a 1 byte anonymous map in memory, instead of an actual file on disk.

**Comment by menify** [comment]
Good idea. But I would check it inside ```_MmapFile.__init__``` and raise an exception.
```try ... except``` better here, because it could catch other unexpected errors related to mmap.
```python
    try:
      self.handle = _MmapFile( filename )
    except Exception:
      self.handle = _IOFile( filename )
```

**Comment by jontayesp** [comment]
Sure, I didn't know if there were other requirements that may cause mmap to fail unexpectedly.

**Comment by jontayesp** [comment]
Fixed in master.
